# Generated by Django 2.1.7 on 2019-03-30 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privada', models.BooleanField(blank=True, null=True, verbose_name='Agenda Privada')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
        migrations.CreateModel(
            name='AgendaInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=128, verbose_name='Ano Institucional')),
            ],
            options={
                'verbose_name': 'Agenda Institucional',
            },
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompromisso', models.CharField(max_length=128, verbose_name='Nome Compromisso')),
                ('dataOcorre', models.DateField(blank=True, null=True, verbose_name='Data do compromisso')),
                ('horaOcorre', models.DateTimeField(blank=True, null=True, verbose_name='Hora do compromisso')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('data_de_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('telefone_celular', models.CharField(blank=True, help_text='Número do telefone celular no formato (99) 99999-9999', max_length=15, null=True, verbose_name='Telefone celular')),
                ('telefone_fixo', models.CharField(blank=True, help_text='Número do telefone celular no formato (99) 99999-9999', max_length=15, null=True, verbose_name='Telefone fixo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AddField(
            model_name='compromisso',
            name='criadorCompromisso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Pessoa'),
        ),
        migrations.AddField(
            model_name='agendainstitucional',
            name='compromisso',
            field=models.ManyToManyField(to='agenda.Compromisso'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='agendaInstitucional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.AgendaInstitucional'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='compromisso',
            field=models.ManyToManyField(to='agenda.Compromisso'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='donoAgenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Pessoa'),
        ),
    ]
